{{ $length := len .Values.cloudmon.secrets }}{{- if ne $length 0 }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cloudmon.fullname" . }}
  labels:
{{ include "cloudmon.labels" . | indent 4 }}
type: Opaque
data:
{{- range .Values.cloudmon.secrets }}
  {{ .key }}: {{ .value | b64enc | quote }}
{{- end }}
{{- end }}