apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "backmon.fullname" . }}
  labels:
    {{- include "backmon.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "backmon.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        {{- $backmon_config_hash := include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        {{- $backmon_secret_hash := include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
        {{- $config_hash := printf "%s%s" $backmon_config_hash $backmon_secret_hash | sha256sum}}
        checksum/config: {{ $config_hash }}
      {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "backmon.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: backmon-config
          configMap:
            name: {{ include "backmon.fullname" . }}
      serviceAccountName: {{ include "backmon.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
          {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
            - mountPath: /etc/backmon/config-raw.yaml
              name: backmon-config
              subPath: config-raw.yaml
          {{- $length := len .Values.backmon.secrets }}{{- if ne $length 0 }}
          envFrom:
            - secretRef:
                name: {{ include "backmon.fullname" . }}
                  {{- end }}
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /api
              port: http
          readinessProbe:
            httpGet:
              path: /api
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
