apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "backmon.fullname" . }}
  labels:
    {{- include "backmon.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "backmon.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        {{- $backmon_secret_hash := include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
        {{- $config_hash := printf "%s" $backmon_secret_hash | sha256sum}}
        checksum/config: {{ $config_hash }}
      {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "backmon.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if or (.Values.backmon.config.enabled) (gt (len .Values.extraVolumes) 0 ) }}
      volumes:
      {{- end }}
      {{- if .Values.backmon.config.enabled }}
        - name: backmon-config
          secret:
            secretName: {{ include "backmon.fullname" . }}
      {{- end }}
      {{- with .Values.extraVolumes }}
      {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "backmon.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
          {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if or (.Values.backmon.config.enabled) (gt (len .Values.extraVolumeMounts) 0 ) }}
          volumeMounts:
          {{- end }}
          {{- if .Values.backmon.config.enabled }}
            - mountPath: /etc/backmon/config.yaml
              name: backmon-config
              subPath: config.yaml
          {{- end }}
          {{- with .Values.extraVolumeMounts }}
          {{- toYaml . | nindent 12 }}
          {{- end }}
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /api
              port: http
          readinessProbe:
            httpGet:
              path: /api
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- if gt (len .Values.extraEnvFrom) 0 }}
          envFrom:
          {{- range .Values.extraEnvFrom }}
            - secretRef:
                name: {{ .name }}
          {{- end }}
          {{- end  }}
          {{- if gt (len .Values.extraEnv) 0 }}
          env:
            {{- toYaml .Values.extraEnv | nindent 12 }}
          {{- end  }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
