{{ $length := len .Values.backmon.secrets }}{{- if ne $length 0 }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "backmon.fullname" . }}
  labels:
{{ include "backmon.labels" . | indent 4 }}
type: Opaque
data:
{{- range .Values.backmon.secrets }}
  {{ .key }}: {{ .value | b64enc | quote }}
{{- end }}
{{- end }}