{{- if .Values.backmon.config.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "backmon.fullname" . }}
  labels:
{{ include "backmon.labels" . | indent 4 }}
data:
  config.yaml: {{ .Values.backmon.config.content | b64enc}}
{{- end }}
