{{ if .Values.serviceMonitor.enabled -}}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "backmon.fullname" . }}
  labels:
    {{- include "backmon.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "backmon.selectorLabels" . | nindent 6 }}
  endpoints:
  - port: http
    path: /metrics
{{- end -}}
