apiVersion: v2
appVersion: "latest"
type: application
description: A Helm chart for psono password manager
icon: https://psono.com/web/image/res.company/1/logo
name: psono
version: 2.2.0
dependencies:
  - name: "postgresql"
    version: "15.2.0"
    repository: "https://charts.bitnami.com/bitnami"
    condition: server.db.bundled
maintainers:
  - name: Thomas Höll
    email: tho@dreitier.com

