apiVersion: v1
kind: Secret
metadata:
  name: {{ include "psono.fileserver.fullname" . }}
  labels:
    {{- include "psono.server.labels" . | nindent 4 }}
data:
  settings.yaml: |-
    {{ tpl ( .Files.Get "files/fileserver-settings.yaml" ) . | b64enc }}
