apiVersion: v1
kind: Service
metadata:
  name: {{ include "psono.fileserver.fullname" . }}
  labels:
    {{- include "psono.fileserver.labels" . | nindent 4 }}
spec:
  type: {{ .Values.fileserver.service.type }}
  ports:
    - port: {{ .Values.fileserver.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "psono.fileserver.matchLabels" . | nindent 4 }}
