{{- if .Values.server.ingress.enabled -}}
{{- $secretName := printf "%s-tls" ( include "psono.server.fullname" . ) }}
{{- $serviceName := include "psono.server.fullname" . }}
{{- $servicePort := .Values.server.service.port -}}
apiVersion: {{ template "ingress.apiVersion" . }}
kind: Ingress
metadata:
  name: {{ template "psono.server.fullname" . }}
  labels:
  {{- include "psono.server.labels" . | nindent 4 }}
  {{- with .Values.server.ingress.annotations }}
  annotations:
  {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if or (.Capabilities.APIVersions.Has "networking.k8s.io/v1/IngressClass") (.Capabilities.APIVersions.Has "networking.k8s.io/v1beta1/IngressClass") }}
  {{- if .Values.server.ingress.ingressClassName }}
  ingressClassName: {{ .Values.server.ingress.ingressClassName }}
  {{- end }}
  {{- end }}
  rules:
    - host: {{ .Values.server.host }}
      http:
        paths:
          - path: "/" {{/*          {{ .Values.server.path }}*/}}
            pathType: Prefix
            backend:
            {{- if .Capabilities.APIVersions.Has "networking.k8s.io/v1/IngressClass" }}
              service:
                name: {{ $serviceName }}
                port:
                  number: {{ $servicePort }}
            {{- else if .Capabilities.APIVersions.Has "networking.k8s.io/v1beta1/IngressClass" }}
              serviceName: {{ $serviceName }}
              servicePort: {{ $servicePort }}
            {{- end }}
  {{- if .Values.server.ingress.tls }}
  tls:
    - hosts:
        - {{ .Values.server.host }}
      secretName: {{ $secretName }}
  {{- end -}}
{{- end -}}