apiVersion: v1
kind: Secret
metadata:
  name: psono-postgres-initdb-secret
  labels:
    {{- include "psono.server.labels" . | nindent 4 }}
data:
  01-create_user.sql: |-
    {{ tpl ( .Files.Get "files/01-create_user.sql" ) . | b64enc }}
  02-create_database.sql: |-
    {{ tpl ( .Files.Get "files/02-create_database.sql" ) . | b64enc }}