apiVersion: v1
kind: Secret
metadata:
  name: {{ include "psono.server.fullname" . }}
  labels:
    {{- include "psono.server.labels" . | nindent 4 }}
data:
  settings.yaml: |-
    {{ tpl ( .Files.Get "files/settings.yaml" ) . | b64enc }}
  dbUser: {{ .Values.server.db.user | b64enc }}
  dbPass: {{ .Values.server.db.password | b64enc }}

