apiVersion: v1
kind: Service
metadata:
  name: {{ include "psono.server.fullname" . }}
  labels:
    {{- include "psono.server.labels" . | nindent 4 }}
spec:
  type: {{ .Values.server.service.type }}
  ports:
    - port: {{ .Values.server.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    {{- if .Values.server.db.metrics.enabled }}
    - port: 9187
      targetPort: pg-metrics
      protocol: TCP
      name: pg-metrics
  {{- end }}
  selector:
    {{- include "psono.server.matchLabels" . | nindent 4 }}
