{{- if .Values.serviceAccounts.server.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
{{- include "psono.server.labels" . | nindent 4 }}
  name: {{ template "psono.serviceAccountName.server" . }}
{{ include "psono.namespace" . | indent 2 }}
  annotations:
{{ toYaml .Values.serviceAccounts.server.annotations | indent 4 }}
{{- end }}