apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "psono.client.fullname" . }}
  labels:
    {{- include "psono.client.labels" . | nindent 4 }}
data:
  config.json: |-
    {
      "backend_servers": [{
        "title": "{{ .Values.server.displayName }}",
        "url": "{{ include "psono.server.externalUrl" .| trimSuffix "/"  }}",
        "domain": {{ .Values.client.logonDomain | quote }}
      }],
      "base_url": "{{ include "psono.client.externalUrl" . | trimSuffix "/" }}",
      "allow_custom_server": {{ .Values.client.allowCustomServer | default false | ternary "true" "false" }},
      "allow_registration": {{ .Values.server.allowRegistration | default false | ternary "true" "false" }},
      "allow_lost_password": {{ .Values.server.allowLostPassword | default false | ternary "true" "false" }},
      "authentication_methods": {{ include "psono.client.auth.methods" . }},
      "saml_provider": [
{{- if .Values.server.saml.enabled }}
      {
        "title": {{ .Values.client.saml.title | quote }},
        "provider_id": 1,
        "button_name": {{ .Values.client.saml.button | quote }}
      }
{{- end }}
      ],
      "oidc_provider": [
{{- if .Values.server.oidc.enabled }}
        {
          "title": {{ .Values.client.oidc.title | quote }},
          "provider_id": 1,
          "button_name": {{ .Values.client.oidc.button | quote }}
        }
{{- end }}
      ]
    }
